// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2wdktY5ZfrkQXuuiZ1J7GuH9mksHPeFk',
    appId: '1:472206340925:web:d34ef4146f24914365cb54',
    messagingSenderId: '472206340925',
    projectId: 'medics-5d574',
    authDomain: 'medics-5d574.firebaseapp.com',
    storageBucket: 'medics-5d574.appspot.com',
    measurementId: 'G-7PS8RC6JKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx--wa_J-qxCsC48p2hkhPeSqh_R2glpU',
    appId: '1:472206340925:android:3f675f02237962d165cb54',
    messagingSenderId: '472206340925',
    projectId: 'medics-5d574',
    storageBucket: 'medics-5d574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo5TbtQhbLlbnGL92nQEuMExawwO-wKt0',
    appId: '1:472206340925:ios:0e9e0bdf0679e24265cb54',
    messagingSenderId: '472206340925',
    projectId: 'medics-5d574',
    storageBucket: 'medics-5d574.appspot.com',
    iosBundleId: 'com.example.medical',
  );
}
